#!/bin/bash

# Fyers Token Regeneration Guide
# This script helps you regenerate the Fyers access token when it expires

echo "🔐 Fyers Token Regeneration Guide"
echo "=================================="
echo ""
echo "Your Fyers API token has expired. Here's how to fix it:"
echo ""
echo "Option 1: Manual Token Update (Quickest)"
echo "----------------------------------------"
echo "1. Login to Fyers: https://myapi.fyers.in/"
echo "2. Go to 'My Apps' → Select your app"
echo "3. Click 'Generate Access Token'"
echo "4. Copy the new token"
echo "5. Update .env file:"
echo "   echo 'FYERS_ACCESS_TOKEN=your_new_token' >> .env"
echo "6. Redeploy: ./deploy_job.sh"
echo ""
echo "Option 2: Use Token Generation Script (Automated)"
echo "------------------------------------------------"
echo "Note: Requires fyers-apiv3 installed locally"
echo ""
echo "1. Activate virtual environment:"
echo "   source venv/bin/activate"
echo ""
echo "2. Install Fyers SDK (if not installed):"
echo "   pip install fyers-apiv3"
echo ""
echo "3. Run token generation:"
echo "   python3 scripts/verify_fyers_token_simple.py"
echo ""
echo "4. Redeploy:"
echo "   ./deploy_job.sh"
echo ""
echo "Option 3: Automatic Token Refresh (Best Long-term)"
echo "--------------------------------------------------"
echo "The system now has automatic token validation:"
echo "- Validates token before each Fyers API call"
echo "- Automatically falls back to yfinance if token invalid"
echo "- Logs clear messages indicating fallback usage"
echo ""
echo "To set up permanent automatic refresh:"
echo "1. Set up Fyers OAuth flow with refresh tokens"
echo "2. Store refresh token securely (Cloud Secret Manager)"
echo "3. Implement token refresh in fyers_interface.py"
echo ""
echo "=================================="
echo "Current Status: System is using yfinance fallback"
echo "Impact: No data loss, but missing real-time Fyers data"
echo "=================================="
